config/routes.rb
Rails.application.routes.draw do
	root to: 'static_pages#root'	


  resources :users, only: [:new, :create, :index, :show, :search] do
  	get "search", on: :collection

  	resource :followings, only: [:create, :destroy]
  end

	  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
	  resources :rides
	end
end

app/models/following.rb
class Following < ActiveRecord::Base
  has_one(
  	:followed_user,
  	class_name: "User",
  	foreign_key: :id,
  	primary_key: :followed_user_id
  )
  belongs_to :user
end

app/models/ride.rb
class Ride < ActiveRecord::Base
	validates :user_id, :title, presence: true

	belongs_to(:user)
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :password_digest, presence: true
	validates :password, length: { minimum: 6, allow_nil: true }

	attr_reader :password

	has_many(:rides)
	has_many(:followings)
	has_many(
		:followed_users,
		through: :followings,
		source: :followed_user
	)
	
	has_many(
		:followed_rides,
		through: :followed_users,
		source: :rides
	)

	after_initialize :ensure_session_token

	def self.find_by_credentials(username, password)
		user = User.find_by(username: username)
		return nil unless user && user.valid_password?(password)
		user
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def valid_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def reset_token!
		self.session_token = SecureRandom.urlsafe_base64(16)
		self.save!
		self.session_token
	end

	private
	def ensure_session_token
		self.session_token ||= SecureRandom.urlsafe_base64(16)
	end
end

app/controllers/api/api_controller.rb
module Api
	class ApiController < ApplicationController
		before_action :require_signed_in!
	end
end

app/controllers/api/rides_controller.rb
module Api
	class RidesController < ApiController
		def new
			@ride = Ride.new
		end

		# def edit
		# 	@ride = Ride.find(params[:id])
		# 	render json: @ride
		# end

		
	    def update
	      @ride = Ride.find(params[:id])
	      if @ride.update_attributes(ride_params)
	        render json: @ride
	      else
	        render json: @ride.errors.full_messages,
           	status: :unprocessable_entity
	      end
	    end

		def create			
			@ride = Ride.new(ride_params)
			@ride.user_id = current_user.id
			@ride.username = current_user.username
			if @ride.save
				render :json => @ride
			else
				flash.now[:errors] = @ride.errors.full_messages
				render :new
			end
		end

		def index
			rides_to_show = []
			rides_to_show.concat(current_user.followed_rides)
			rides_to_show.concat(current_user.rides)
			
			@ride_set = rides_to_show
			
			render json: @ride_set
		end

		def show
			@ride = Ride.find(params[:id])
			render json: @ride
		end

		private
		def ride_params
			params.require(:ride).permit(:user_id, :username, :title, :date, :directions, :distance, :elevation)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
  	@current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
  	!!current_user
  end

  def sign_in(user)
  	@current_user = user
  	session[:session_token] = user.reset_token!
  end

  def sign_out
  	current_user.try(:reset_token!)
  	session[:session_token] = nil
  end

  def require_signed_in!
  	redirect_to new_user_url unless signed_in?
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
	before_action :require_signed_in!

	def create
		sleep(1)

		followed_user_id = params[:user_id]
		user_to_follow = User.find(params[:user_id])

		if (!current_user.followed_users.include?(user_to_follow))
			@follow = Following.create!({user_id: current_user.id,
				followed_user_id: followed_user_id});

			render json: @follow
		else
			@follow = current_user.followings.find_by(followed_user_id: params[:user_id])
			@follow.destroy!

			render json: @follow
		end
	end

	def destroy
		sleep(1)

		@follow = current_user.followings.find_by(followed_user_id: params[:user_id])
		@follow.destroy!

		render json: @follow
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_credentials(
			params[:user][:username],
			params[:user][:password]
		)

		if user
			sign_in(user)
			redirect_to '#'
		else
			flash.now[:errors] = ["Invalid username or password"]
			render :new
		end
	end

	def destroy
		if current_user.username == "Guest"
			rides = Ride.where(username: "Guest")
			newrides = rides.where("created_at > ?", Time.gm(2014, 12, 16))
			newrides.destroy_all
		end
		sign_out
		redirect_to new_session_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def index
		#cheating -- using this as a show route for the current user. 
		#this gets used in the index, but there's almost surely a better way to 
		#do the same thing
		@user = current_user
		render json: @user
	end

	def show
		@user = User.find(params[:id])
		render json: @user
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in(@user)
			redirect_to root_url
		else
			flash.now[:errors] = @user.errors.full_messages
			render :new
		end
	end

	def search
		if params[:query].present?
			@users = User.where("username ~ ?", params[:query])
		else
			@users = User.none
		end

		render json: @users
		# respond_to do |format|
		# 	format.html { render :search }
		# 	format.json { render :search }
		# end
	end

	private
	def user_params
		params.require(:user).permit(:password, :username)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def auth_token_input
	"<input type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
	end
	
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div>
	<head>
	  <title>RouteMapper</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBEol9AdAZ6s6pgZLn9uIfcSdJn7oOwXmU">
</script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
 
	  <%= csrf_meta_tags %>
	</head>
  <header>
        <nav class="navbar navbar-inverse navbar-fixed-top nav-fixed-height" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RouteMapper</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
                <li><%= link_to "Sign Out", session_url, method: :delete %></li>
                <li><a href="#rides/new">New Ride</a></li>
                <li><a href="#">Activity Feed</a></li>
                <li><a href="#rides/my">My Rides</a></li>
                <li id="current-username"><%= current_user.username %></li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="users-search">
              <input type="text" class="form-control" name="username" placeholder="Follow - coming soon!">
              <ul class="users"></ul>
            </div>
          </form>
          <% else %>
            <li><%= link_to "Sign In", new_session_url %></li>
            <li><%= link_to "Sign Up", new_user_url %></li>
          </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </header>
	<body>
    <div class="container-fluid">
  		<div class="row">
  			<%= yield %>
  		</div>
    </div>
	</body>
</div>
</html>

app/views/rides/index.html.erb
<!-- historical, moved to backbone -->
<h2>Rides</h2>
<% @rides.each do |ride| %>
	<div><%= ride.title %> <%= ride.date %></div><br>
<% end %>

app/views/rides/new.html.erb
<h2>New Ride</h2>


<form action="<%= rides_url %>" method="post"> 
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="ride[title]" value="">
  </label>

  <label>
    Date
    <input type="date" name="ride[date]" value="">
  </label>

    <input type="hidden" name="ride[user_id]" value="<%= current_user.id %>">

  <input type="submit" value="Sign Up">
</form>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <div id="content"></div>
</div>
<script>$(RouteMapper.initialize);</script>

app/views/users/new.html.erb
<script src="//fast.eager.io/cy3GIbLbj0.js"></script>
<div class="sign_in">
  <form class="form-signin" role="form" action="<%= users_url %>" method="post"> 
    <%= auth_token_input %>
    <h2 class="form-signin-heading">Sign up</h2>

    <label for="inputUsername" id="username" class="sr-only">Username</label>
      <input type="text" id="inputEmail" class="form-control" name="user[username]" value="Guest" required autofocus>

    <label for="inputPassword" class="sr-only" id="password">Password</label>
      <input type="password" id="inputPassword" class="form-control" name="user[password]" value="catlover" required autofocus>

    <label id="login">
      <input type="submit" value="Sign Up">
    </label>
  </form>
</div>

app/views/users/search.html.erb
<h1>Search!</h1>

<div class="users-search">
  <label>
    Username
    <input type="text" name="username">

  </label>

  <h4>Result</h4>
  <ul class="users"></ul>
</div>